OBJECTS		= 
LIBRARIES	=
PROGRAMS	= fork_exec fork print_pid sigchld sigusr1 system zombie

.PHONY:         all clean

# Default target: build everything.
all:            $(OBJECTS) $(LIBRARIES) $(PROGRAMS)

# Clean up build products.
clean:
	rm -f *.o *.a $(PROGRAMS)
